# Generated by Django 5.1.4 on 2025-01-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VacStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_salary_chart', models.ImageField(upload_to='', verbose_name='График зарплат по годам Java-программист')),
                ('annual_salary_data', models.TextField(verbose_name='Таблица зарплат по годам Java-программист')),
                ('annual_vacancy_chart', models.ImageField(upload_to='', verbose_name='График количества вакансий по годам Java-программист')),
                ('annual_vacancy_data', models.TextField(verbose_name='Таблица количества вакансий по годам Java-программист')),
            ],
            options={
                'verbose_name': 'Востребованность',
                'verbose_name_plural': 'Востребованности',
            },
        ),
    ]
