# Generated by Django 5.1.4 on 2025-01-20 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillsstatistics',
            old_name='top20_skills_java_2015_data',
            new_name='data_table_top20_sks_java_2015',
        ),
        migrations.RenameField(
            model_name='skillsstatistics',
            old_name='top20_skills_java_2016_data',
            new_name='data_table_top20_sks_java_2016',
        ),
        migrations.RenameField(
            model_name='skillsstatistics',
            old_name='top20_skills_java_2017_data',
            new_name='data_table_top20_sks_java_2017',
        ),
        migrations.RenameField(
            model_name='skillsstatistics',
            old_name='top20_skills_java_2018_data',
            new_name='data_table_top20_sks_java_2018',
        ),
        migrations.RenameField(
            model_name='skillsstatistics',
            old_name='top20_skills_java_2019_data',
            new_name='data_table_top20_sks_java_2019',
        ),
        migrations.RenameField(
            model_name='skillsstatistics',
            old_name='top20_skills_java_2020_data',
            new_name='data_table_top20_sks_java_2020',
        ),
        migrations.RenameField(
            model_name='skillsstatistics',
            old_name='top20_skills_java_2021_data',
            new_name='data_table_top20_sks_java_2021',
        ),
        migrations.RenameField(
            model_name='skillsstatistics',
            old_name='top20_skills_java_2022_data',
            new_name='data_table_top20_sks_java_2022',
        ),
        migrations.RenameField(
            model_name='skillsstatistics',
            old_name='top20_skills_java_2023_data',
            new_name='data_table_top20_sks_java_2023',
        ),
        migrations.RenameField(
            model_name='skillsstatistics',
            old_name='top20_skills_java_2024_data',
            new_name='data_table_top20_sks_java_2024',
        ),
        migrations.RenameField(
            model_name='skillsstatistics',
            old_name='top20_skills_java_2015_graph',
            new_name='graph_top20_sks_java_2015',
        ),
        migrations.RenameField(
            model_name='skillsstatistics',
            old_name='top20_skills_java_2016_graph',
            new_name='graph_top20_sks_java_2016',
        ),
        migrations.RenameField(
            model_name='skillsstatistics',
            old_name='top20_skills_java_2017_graph',
            new_name='graph_top20_sks_java_2017',
        ),
        migrations.RenameField(
            model_name='skillsstatistics',
            old_name='top20_skills_java_2018_graph',
            new_name='graph_top20_sks_java_2018',
        ),
        migrations.RenameField(
            model_name='skillsstatistics',
            old_name='top20_skills_java_2019_graph',
            new_name='graph_top20_sks_java_2019',
        ),
        migrations.RenameField(
            model_name='skillsstatistics',
            old_name='top20_skills_java_2020_graph',
            new_name='graph_top20_sks_java_2020',
        ),
        migrations.RenameField(
            model_name='skillsstatistics',
            old_name='top20_skills_java_2021_graph',
            new_name='graph_top20_sks_java_2021',
        ),
        migrations.RenameField(
            model_name='skillsstatistics',
            old_name='top20_skills_java_2022_graph',
            new_name='graph_top20_sks_java_2022',
        ),
        migrations.RenameField(
            model_name='skillsstatistics',
            old_name='top20_skills_java_2023_graph',
            new_name='graph_top20_sks_java_2023',
        ),
        migrations.RenameField(
            model_name='skillsstatistics',
            old_name='top20_skills_java_2024_graph',
            new_name='graph_top20_sks_java_2024',
        ),
    ]
