# Generated by Django 5.1.4 on 2025-01-20 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geography_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacgeostats',
            old_name='salary_table_by_city',
            new_name='data_table_java_sal_by_city',
        ),
        migrations.RenameField(
            model_name='vacgeostats',
            old_name='vac_share_table_by_city',
            new_name='data_table_java_vac_share_by_city',
        ),
        migrations.RenameField(
            model_name='vacgeostats',
            old_name='vac_share_graph_by_city',
            new_name='graph_java_vac_share_by_city',
        ),
        migrations.RenameField(
            model_name='vacgeostats',
            old_name='salary_graph_by_city',
            new_name='graph_sal_by_city',
        ),
    ]
