# Generated by Django 5.1.4 on 2025-01-20 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latest_vacs_page', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
