# Generated by Django 5.1.4 on 2025-01-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_salary_chart', models.ImageField(upload_to='', verbose_name='График зарплат по годам')),
                ('annual_salary_data', models.TextField(verbose_name='Таблица зарплат по годам')),
                ('annual_vacancy_chart', models.ImageField(upload_to='', verbose_name='График количества вакансий по годам')),
                ('annual_vacancy_data', models.TextField(verbose_name='Таблица количества вакансий по годам')),
                ('city_salary_chart', models.ImageField(upload_to='', verbose_name='График зарплат по городам')),
                ('city_salary_data', models.TextField(verbose_name='Таблица зарплат по городам')),
                ('city_vacancy_share_chart', models.ImageField(upload_to='', verbose_name='График долей вакансий по городам')),
                ('city_vacancy_share_data', models.TextField(verbose_name='Таблица доли вакансий по городам')),
                ('top_skills_chart', models.ImageField(upload_to='', verbose_name='График ТОП-20 навыков')),
                ('top_skills_data', models.TextField(verbose_name='Таблица ТОП-20 навыков')),
            ],
        ),
    ]
