# Generated by Django 5.1.4 on 2025-01-13 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_stats_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistics',
            options={'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистики'},
        ),
    ]
