# Generated by Django 5.1.4 on 2025-01-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_stats_page', '0002_alter_statistics_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='top_skills_chart',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='top_skills_data',
        ),
        migrations.AddField(
            model_name='statistics',
            name='top_skills_2015_chart',
            field=models.ImageField(default=None, upload_to='', verbose_name='График ТОП-20 навыков за 2015 год'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='top_skills_2015_data',
            field=models.TextField(default=None, verbose_name='Таблица ТОП-20 навыков за 2015 год'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='top_skills_2016_chart',
            field=models.ImageField(default=None, upload_to='', verbose_name='График ТОП-20 навыков за 2016 год'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='top_skills_2016_data',
            field=models.TextField(default=None, verbose_name='Таблица ТОП-20 навыков за 2016 год'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='top_skills_2017_chart',
            field=models.ImageField(default=None, upload_to='', verbose_name='График ТОП-20 навыков за 2017 год'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='top_skills_2017_data',
            field=models.TextField(default=None, verbose_name='Таблица ТОП-20 навыков за 2017 год'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='top_skills_2018_chart',
            field=models.ImageField(default=None, upload_to='', verbose_name='График ТОП-20 навыков за 2018 год'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='top_skills_2018_data',
            field=models.TextField(default=None, verbose_name='Таблица ТОП-20 навыков за 2018 год'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='top_skills_2019_chart',
            field=models.ImageField(default=None, upload_to='', verbose_name='График ТОП-20 навыков за 2019 год'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='top_skills_2019_data',
            field=models.TextField(default=None, verbose_name='Таблица ТОП-20 навыков за 2019 год'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='top_skills_2020_chart',
            field=models.ImageField(default=None, upload_to='', verbose_name='График ТОП-20 навыков за 2020 год'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='top_skills_2020_data',
            field=models.TextField(default=None, verbose_name='Таблица ТОП-20 навыков за 2020 год'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='top_skills_2021_chart',
            field=models.ImageField(default=None, upload_to='', verbose_name='График ТОП-20 навыков за 2021 год'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='top_skills_2021_data',
            field=models.TextField(default=None, verbose_name='Таблица ТОП-20 навыков за 2021 год'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='top_skills_2022_chart',
            field=models.ImageField(default=None, upload_to='', verbose_name='График ТОП-20 навыков за 2022 год'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='top_skills_2022_data',
            field=models.TextField(default=None, verbose_name='Таблица ТОП-20 навыков за 2022 год'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='top_skills_2023_chart',
            field=models.ImageField(default=None, upload_to='', verbose_name='График ТОП-20 навыков за 2023 год'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='top_skills_2023_data',
            field=models.TextField(default=None, verbose_name='Таблица ТОП-20 навыков за 2023 год'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='top_skills_2024_chart',
            field=models.ImageField(default=None, upload_to='', verbose_name='График ТОП-20 навыков за 2024 год'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='top_skills_2024_data',
            field=models.TextField(default=None, verbose_name='Таблица ТОП-20 навыков за 2024 год'),
            preserve_default=False,
        ),
    ]
